---
# FIRE snapshot number and simulation id (user specific)
snap : 385 
sim : 'm12i'
# Simulation directory and satellite ids location (user specific)
sim_dir : '/home/jovyan/data/fire2/m12i_res7100/'
sat_id_dir : '/home/jovyan/home/tracked/m12b/all_LMC_inds.txt'
# Min and max radius [kpc]
rmin : 20
rmax : 300
# Min and max value for healpy.newvisufunc.projview used in mollweide_plotting.py
bmin : -1
bmax : 1
# If True, creates mollweide plot of overdensity 
overdensity : True
# If True, removes the satellite using satellite ids (mutually exclusive to only_sat_mask)
sat_mask : True
# If True, keeps only the satellite using satellite ids (mutually exclusive to sat_mask)
only_sat_mask : False
# If True, removes the halo using rmin and rmax
halo_mask : True
# If True, randomly subsamples a number of particles equal to the subsample value
rand_mask : True
subsample : 10000
# Ananke parameters
ananke_name : 'sim_anankethon'
photo_sys : 'padova/WFIRST-HST'
cmd_magnames: 'F814W,F555W-F814W'
app_mag_lim_lo: -1000.0
app_mag_lim_hi: 1000.0
abs_mag_lim_lo: -1000.0
abs_mag_lim_hi: 5.0
ananke_r_max: 1000
...